# Generated by Django 4.2.3 on 2023-10-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_book',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
